[tools]
go = ["1.25.4"]
rust = { version = "latest", profile = "minimal" }
node = "latest"

bat = "latest"
claude-code = "latest"
fd = "latest"
fzf = "latest"
lsd = "latest"
ripgrep = "latest"
starship = "latest"
usage = "latest"
